//! One workspace YAML → `relay.yaml`, `tunnels.yaml`, and Caddy site blocks stay aligned.

use std::collections::{BTreeMap, BTreeSet};
use std::fs;
use std::net::SocketAddr;
use std::path::{Path, PathBuf};

use anyhow::{Context, Result, bail};
use clap::{Parser, Subcommand};
use serde::{Deserialize, Serialize};

const HEADER_YAML: &str = "# Generated by tunnelion-config\n";
const HEADER_CADDY: &str =
    "# Generated by tunnelion-config\n# DNS for each host must point at this VPS.\n\n";

#[derive(Parser)]
#[command(
    name = "tunnelion-config",
    about = "Sync relay, client, and Caddy from one workspace file"
)]
struct Cli {
    #[command(subcommand)]
    cmd: Command,
}

#[derive(Subcommand)]
enum Command {
    /// Parse workspace and verify addresses, unique hosts, unique listen ports
    Check {
        #[arg(value_name = "WORKSPACE")]
        path: PathBuf,
    },
    /// Generate relay.yaml, tunnels.yaml, and/or Caddy (see `emit all`)
    Emit {
        #[command(subcommand)]
        target: EmitTarget,
    },
}

#[derive(Subcommand)]
enum EmitTarget {
    /// Write relay.yaml, tunnels.yaml, and caddy-tunnelion.caddy into one directory
    All {
        #[arg(short, long, value_name = "WORKSPACE")]
        input: PathBuf,
        #[arg(
            long,
            value_name = "HOST:PORT",
            help = "Client-visible relay control socket (e.g. 203.0.113.50:9780)"
        )]
        relay_addr: String,
        #[arg(
            short,
            long,
            value_name = "DIR",
            help = "Output directory (created if missing)"
        )]
        out_dir: PathBuf,
    },
    /// Print relay.yaml body (stdout)
    Relay {
        #[arg(short, long, value_name = "WORKSPACE")]
        input: PathBuf,
    },
    /// Print tunnels.yaml body (stdout). Requires public relay control address.
    Client {
        #[arg(short, long, value_name = "WORKSPACE")]
        input: PathBuf,
        #[arg(
            long,
            value_name = "HOST:PORT",
            help = "Client-visible relay control socket (e.g. 203.0.113.50:9780)"
        )]
        relay_addr: String,
    },
    /// Print Caddy site blocks (stdout, tab-indented)
    Caddy {
        #[arg(short, long, value_name = "WORKSPACE")]
        input: PathBuf,
    },
}

#[derive(Debug, Deserialize)]
struct Workspace {
    control: ControlSpec,
    tunnels: BTreeMap<String, TunnelSpec>,
}

#[derive(Debug, Deserialize)]
struct ControlSpec {
    addr: String,
}

#[derive(Debug, Deserialize)]
struct TunnelSpec {
    /// Relay-side public listen (must match Caddy reverse_proxy target)
    listen: String,
    /// Client-side upstream (port or host:port)
    client_addr: String,
    /// Hostname for TLS / Caddy site block
    host: String,
}

#[derive(Serialize)]
struct RelayYamlOut<'a> {
    control: ControlOut<'a>,
    tunnels: BTreeMap<&'a str, ListenOut<'a>>,
}

#[derive(Serialize)]
struct ControlOut<'a> {
    addr: &'a str,
}

#[derive(Serialize)]
struct ListenOut<'a> {
    listen: &'a str,
}

#[derive(Serialize)]
struct ClientYamlOut<'a> {
    relay: ClientRelayOut<'a>,
    tunnels: BTreeMap<&'a str, ClientTunnelOut<'a>>,
}

#[derive(Serialize)]
struct ClientRelayOut<'a> {
    addr: &'a str,
}

#[derive(Serialize)]
struct ClientTunnelOut<'a> {
    addr: &'a str,
    domain: &'a str,
}

fn load_workspace(path: &PathBuf) -> Result<Workspace> {
    let s = fs::read_to_string(path).with_context(|| format!("read {}", path.display()))?;
    let w: Workspace = serde_yaml::from_str(&s).context("parse workspace yaml")?;
    if w.tunnels.is_empty() {
        bail!("workspace: tunnels: need at least one tunnel");
    }
    Ok(w)
}

fn validate_workspace(w: &Workspace) -> Result<()> {
    w.control
        .addr
        .parse::<SocketAddr>()
        .context("control.addr must be a socket address")?;

    let mut listens = BTreeSet::new();
    let mut hosts = BTreeSet::new();

    for (name, t) in &w.tunnels {
        let la: SocketAddr = t
            .listen
            .parse()
            .with_context(|| format!("tunnels.{name}.listen"))?;
        if !listens.insert(la) {
            bail!("duplicate relay listen {la} (tunnels.{name})");
        }
        let h = t.host.trim();
        if h.is_empty() {
            bail!("tunnels.{name}.host must be non-empty");
        }
        if !hosts.insert(h.to_string()) {
            bail!("duplicate host {h:?} (tunnels.{name})");
        }
        if t.client_addr.trim().is_empty() {
            bail!("tunnels.{name}.client_addr must be non-empty");
        }
    }

    Ok(())
}

fn emit_relay(w: &Workspace) -> Result<String> {
    let mut tunnels = BTreeMap::new();
    for (name, t) in &w.tunnels {
        tunnels.insert(
            name.as_str(),
            ListenOut {
                listen: t.listen.as_str(),
            },
        );
    }
    let out = RelayYamlOut {
        control: ControlOut {
            addr: w.control.addr.as_str(),
        },
        tunnels,
    };
    let mut s = String::from(HEADER_YAML);
    s.push_str(&serde_yaml::to_string(&out)?);
    Ok(s)
}

fn emit_client(w: &Workspace, relay_addr: &str) -> Result<String> {
    relay_addr
        .parse::<SocketAddr>()
        .context("--relay-addr must be host:port")?;

    let mut tunnels = BTreeMap::new();
    for (name, t) in &w.tunnels {
        tunnels.insert(
            name.as_str(),
            ClientTunnelOut {
                addr: t.client_addr.as_str(),
                domain: t.host.as_str(),
            },
        );
    }
    let out = ClientYamlOut {
        relay: ClientRelayOut { addr: relay_addr },
        tunnels,
    };
    let mut s = String::from(HEADER_YAML);
    s.push_str(&serde_yaml::to_string(&out)?);
    Ok(s)
}

fn emit_caddy(w: &Workspace) -> Result<String> {
    let mut s = String::from(HEADER_CADDY);
    for t in w.tunnels.values() {
        s.push_str(&format!("{} {{\n", t.host));
        s.push_str("\treverse_proxy ");
        s.push_str(t.listen.trim());
        s.push_str("\n}\n\n");
    }
    Ok(s)
}

fn write_all_artifacts(w: &Workspace, relay_addr: &str, out_dir: &Path) -> Result<()> {
    fs::create_dir_all(out_dir).with_context(|| format!("create {}", out_dir.display()))?;

    let relay_path = out_dir.join("relay.yaml");
    let tunnels_path = out_dir.join("tunnels.yaml");
    let caddy_path = out_dir.join("caddy-tunnelion.caddy");

    fs::write(&relay_path, emit_relay(w)?)
        .with_context(|| format!("write {}", relay_path.display()))?;
    fs::write(&tunnels_path, emit_client(w, relay_addr)?)
        .with_context(|| format!("write {}", tunnels_path.display()))?;
    fs::write(&caddy_path, emit_caddy(w)?)
        .with_context(|| format!("write {}", caddy_path.display()))?;

    eprintln!(
        "wrote {} {} {}",
        relay_path.display(),
        tunnels_path.display(),
        caddy_path.display()
    );
    Ok(())
}

fn main() -> Result<()> {
    let cli = Cli::parse();
    match cli.cmd {
        Command::Check { path } => {
            let w = load_workspace(&path)?;
            validate_workspace(&w)?;
            eprintln!(
                "ok: {} tunnel(s), control {}",
                w.tunnels.len(),
                w.control.addr
            );
        }
        Command::Emit { target } => match target {
            EmitTarget::All {
                input,
                relay_addr,
                out_dir,
            } => {
                let w = load_workspace(&input)?;
                validate_workspace(&w)?;
                write_all_artifacts(&w, relay_addr.trim(), &out_dir)?;
            }
            EmitTarget::Relay { input } => {
                let w = load_workspace(&input)?;
                validate_workspace(&w)?;
                print!("{}", emit_relay(&w)?);
            }
            EmitTarget::Client { input, relay_addr } => {
                let w = load_workspace(&input)?;
                validate_workspace(&w)?;
                print!("{}", emit_client(&w, relay_addr.trim())?);
            }
            EmitTarget::Caddy { input } => {
                let w = load_workspace(&input)?;
                validate_workspace(&w)?;
                print!("{}", emit_caddy(&w)?);
            }
        },
    }
    Ok(())
}
